### ISSUE TITLE
编译不过啊 framebufferColorTexture没有

### ISSUE THREAD

**Issue by HJC1990** [SquarePants1991/OpenGLESLearn#2]
createTextureFramebuffer这个方法里面framebufferColorTexture这个没有啊

**Comment by SquarePants1991** [comment]
是哪个分支下的？麻烦告诉一下。我去修复一下。

**Comment by HJC1990** [comment]
就是这个OpenGLESLearn下载下来的

**Comment by SquarePants1991** [comment]
master上的代码最近没怎么维护，一般都是最新的分支合并过去的代码。我写的博客示例代码都在对应的分支下，现在我把chapter28的代码合并到master上了，编译不会有问题了。

**Comment by HJC1990** [comment]
编译成功。。。厉害了 这个游戏

**Comment by HJC1990** [comment]
大神 你的博客地址是哪个啊？

**Comment by SquarePants1991** [comment]
博客地址 [http://www.gltech.win/](http://www.gltech.win/)，或者也可以访问我的简书 [http://www.jianshu.com/u/e6367cf15710](http://www.jianshu.com/u/e6367cf15710)。话说你是从哪找到我这个git项目的？

**Comment by HJC1990** [comment]
我想学习OpenGL，然后就搜OpenGL学习 learn 之类的，是不是太土了

**Comment by SquarePants1991** [comment]
挺正常的，善于搜索是程序员重要技能之一😄

**Comment by HJC1990** [comment]
哈哈 博主多更新，我学习学习
