### ISSUE TITLE
下面这句编译失败

### ISSUE THREAD

**Issue by jj89757hhb** [SquarePants1991/OpenGLESLearn#3]
glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, framebufferColorTexture, 0);

**Comment by SquarePants1991** [comment]
是哪个分支下的？麻烦告诉一下。我去修复一下。

**Comment by jj89757hhb** [comment]
https://github.com/SquarePants1991/OpenGLESLearn   然后点击down

**Comment by SquarePants1991** [comment]
master上的代码最近没怎么维护，一般都是最新的分支合并过去的代码。我写的博客示例代码都在对应的分支下，现在我把chapter28的代码合并到master上了，编译不会有问题了。
